In [1]:
import pandas as pd 
df1=pd.read_csv("customer_orders.csv")
df2=pd.read_csv("orders.csv")
df3=pd.read_csv("customers.csv")
df4=pd.read_csv("food_delivery_data.csv")

In [2]:
df1.head()

,Customer_ID,Customer_Name,City,Age,Order_Amount,Payment_Method,Order_Date,Rating
0,124,Rahul,Delhi,120.0,-500,Wallet,23-01-2025,2.0
1,132,Ravi,Bangalore,26.0,-500,Card,20/01/2025,NaN
2,104,Priya,NaN,53.0,-500,COD,09-02-2025,2.0
3,135,Sneha,NaN,-5.0,99999,UPI,06-01-2025,4.0
4,140,Amit,NaN,NaN,99999,UPI,13-01-2025,2.0

In [3]:
df2.head()

   Order_ID  Customer_ID  Amount
0       200           17    4519
1       201          123    3761
2       202           82    3358
3       203            7    1155
4       204          112    5173

In [4]:
df3.head()

   Customer_ID   Name       City
0            1   Ravi  Bangalore
1            2   Neha     Mumbai
2            3   Amit     Mumbai
3            4  Kavya     Mumbai
4            5   Amit      Delhi

In [5]:
df4.head()

,Order_ID,City,Restaurant,Order_Value,Delivery_Time,Rating,Payment_Method
0,1,Bangalore,Spice Hub,1531.0,16,3.0,Card
1,2,Hyderabad,Urban Plate,6100.0,37,5.0,Wallet
2,3,Delhi,Spice Hub,-300.0,120,3.0,Card
3,4,Hyderabad,Food Corner,-300.0,120,NaN,Card
4,5,Chennai,Curry House,NaN,52,1.0,UPI

In [6]:
df1.shape

(170, 8)

In [7]:
df2.shape

(180, 3)

In [8]:
df3.shape

(160, 3)

In [9]:
df4.shape

(170, 7)

In [10]:
df1.columns
df1.dtypes

Customer_ID         int64
Customer_Name      object
City               object
Age               float64
Order_Amount        int64
Payment_Method     object
Order_Date         object
Rating            float64
dtype: object

In [11]:
df1.isnull().sum()

Customer_ID        0
Customer_Name      0
City              23
Age               42
Order_Amount       0
Payment_Method     0
Order_Date         0
Rating            28
dtype: int64

In [12]:
#df1["Age"]=pd.to_numeric(df1["Age"],errors="coerce")
df1["Age"].fillna(df1["Age"].mean(),inplace=True)
df1.isnull().sum()

C:\Users\harsh\AppData\Local\Temp\ipykernel_10720\2987653603.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Age"].fillna(df1["Age"].mean(),inplace=True)

Customer_ID        0
Customer_Name      0
City              23
Age                0
Order_Amount       0
Payment_Method     0
Order_Date         0
Rating            28
dtype: int64

In [13]:
df1["Rating"].fillna(df1["Rating"].mean(),inplace=True)
df1.isnull().sum()

C:\Users\harsh\AppData\Local\Temp\ipykernel_10720\1010971731.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Rating"].fillna(df1["Rating"].mean(),inplace=True)

Customer_ID        0
Customer_Name      0
City              23
Age                0
Order_Amount       0
Payment_Method     0
Order_Date         0
Rating             0
dtype: int64

In [14]:
#df1["City"].fillna(df1["City"].mode()[0],inplace=True)

In [15]:
df1.isnull().sum()

Customer_ID        0
Customer_Name      0
City              23
Age                0
Order_Amount       0
Payment_Method     0
Order_Date         0
Rating             0
dtype: int64

In [16]:
df1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
165    False
166    False
167    False
168    False
169    False
Length: 170, dtype: bool

In [17]:
cat_col=df1.select_dtypes(include=["object","category"]).columns
for col in cat_col:
    df1[col].fillna(df1[col].mode()[0],inplace=True)
df1.isnull().sum()

C:\Users\harsh\AppData\Local\Temp\ipykernel_10720\437699477.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1[col].fillna(df1[col].mode()[0],inplace=True)

Customer_ID       0
Customer_Name     0
City              0
Age               0
Order_Amount      0
Payment_Method    0
Order_Date        0
Rating            0
dtype: int64

In [18]:
df1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
165    False
166    False
167    False
168    False
169    False
Length: 170, dtype: bool

In [19]:
df1.drop_duplicates()

,Customer_ID,Customer_Name,City,Age,Order_Amount,Payment_Method,Order_Date,Rating
0,124,Rahul,Delhi,120.000000,-500,Wallet,23-01-2025,2.000000
1,132,Ravi,Bangalore,26.000000,-500,Card,20/01/2025,2.985915
2,104,Priya,delhi,53.000000,-500,COD,09-02-2025,2.000000
3,135,Sneha,delhi,-5.000000,99999,UPI,06-01-2025,4.000000
4,140,Amit,delhi,57.273438,99999,UPI,13-01-2025,2.000000
...,...,...,...,...,...,...,...,...
165,138,Anjali,delhi,-5.000000,99999,Card,2025/02/28,2.000000
166,128,Kavya,Delhi,42.000000,99999,Wallet,22/01/2025,5.000000
167,129,Amit,delhi,57.000000,99999,Wallet,05-02-2025,4.000000
168,130,Vikram,Mumbai,-5.000000,-500,Card,30/01/2025,1.000000
169,130,Rahul,Kolkata,53.000000,-500,Card,22/02/2025,3.000000

In [20]:
df1[df1["Order_Amount"]<0]

,Customer_ID,Customer_Name,City,Age,Order_Amount,Payment_Method,Order_Date,Rating
0,124,Rahul,Delhi,120.000000,-500,Wallet,23-01-2025,2.000000
1,132,Ravi,Bangalore,26.000000,-500,Card,20/01/2025,2.985915
2,104,Priya,delhi,53.000000,-500,COD,09-02-2025,2.000000
9,117,Arjun,mumbai,120.000000,-500,Wallet,01-02-2025,2.985915
11,101,Vikram,delhi,-5.000000,-500,Wallet,22/02/2025,1.000000
...,...,...,...,...,...,...,...,...
152,103,Ravi,Kolkata,120.000000,-500,UPI,2025/02/15,5.000000
158,110,Anjali,Delhi,57.273438,-500,COD,2025/02/15,2.985915
160,124,Arjun,Bangalore,120.000000,-500,Wallet,2025/02/02,4.000000
168,130,Vikram,Mumbai,-5.000000,-500,Card,30/01/2025,1.000000
169,130,Rahul,Kolkata,53.000000,-500,Card,22/02/2025,3.000000

In [21]:
df1[(df1["Age"]<15) | (df1["Age"]>100)]

,Customer_ID,Customer_Name,City,Age,Order_Amount,Payment_Method,Order_Date,Rating
0,124,Rahul,Delhi,120.0,-500,Wallet,23-01-2025,2.000000
3,135,Sneha,delhi,-5.0,99999,UPI,06-01-2025,4.000000
9,117,Arjun,mumbai,120.0,-500,Wallet,01-02-2025,2.985915
11,101,Vikram,delhi,-5.0,-500,Wallet,22/02/2025,1.000000
14,130,Anjali,Delhi,120.0,5283,COD,05/01/2025,1.000000
...,...,...,...,...,...,...,...,...
159,107,Rahul,Bangalore,-5.0,99999,COD,04-02-2025,2.000000
160,124,Arjun,Bangalore,120.0,-500,Wallet,2025/02/02,4.000000
163,130,Priya,delhi,-5.0,99999,COD,2025/02/12,2.000000
165,138,Anjali,delhi,-5.0,99999,Card,2025/02/28,2.000000
168,130,Vikram,Mumbai,-5.0,-500,Card,30/01/2025,1.000000

In [22]:
df4[df4["Delivery_Time"]>120]

Empty DataFrame
Columns: [Order_ID, City, Restaurant, Order_Value, Delivery_Time, Rating, Payment_Method]
Index: []

In [27]:
df1["Order_Date"] = pd.to_datetime(df1["Order_Date"],errors="coerce")

df1.dtypes

Customer_ID                int64
Customer_Name             object
City                      object
Age                      float64
Order_Amount               int64
Payment_Method            object
Order_Date        datetime64[ns]
Rating                   float64
dtype: object

In [33]:
def detect_outliers(df,col):
    q1=df[col].quantile(0.25)
    q3=df[col].quantile(0.75)
    iqr=q3-q1
    lower=q1-1.5*iqr
    upper=q3+1.5*iqr
    outliers=df[(df[col]>lower) | (df[col]<upper)]
    return outliers 
detect_outliers(df1,"Order_Amount")
detect_outliers(df4,"Order_Value")
detect_outliers(df4,"Delivery_Time")
mean_val = df1["Order_Amount"].mean()
q1=df[col].quantile(0.25)
q3=df[col].quantile(0.75)
iqr=q3-q1
lower=q1-1.5*iqr
upper=q3+1.5*iqr
df1.loc[df1["Order_Amount"] > upper, "Order_Amount"] = mean_val
df1.loc[df1["Order_Amount"] < lower, "Order_Amount"] = mean_val

NameError: name 'df' is not defined

In [38]:
from scipy import stats
num_col=df1.select_dtypes(include=["int64","float64"]).columns
z_scores = df1[num_col].apply(stats.zscore)
threshold = 3
df_cleaned = df1[(z_scores.abs() <= threshold).all(axis=1)]
df_cleaned

,Customer_ID,Customer_Name,City,Age,Order_Amount,Payment_Method,Order_Date,Rating
0,124,Rahul,Delhi,120.000000,-500,Wallet,2025-01-23,2.000000
1,132,Ravi,Bangalore,26.000000,-500,Card,NaT,2.985915
2,104,Priya,delhi,53.000000,-500,COD,2025-02-09,2.000000
3,135,Sneha,delhi,-5.000000,99999,UPI,2025-01-06,4.000000
4,140,Amit,delhi,57.273438,99999,UPI,2025-01-13,2.000000
...,...,...,...,...,...,...,...,...
165,138,Anjali,delhi,-5.000000,99999,Card,NaT,2.000000
166,128,Kavya,Delhi,42.000000,99999,Wallet,NaT,5.000000
167,129,Amit,delhi,57.000000,99999,Wallet,2025-02-05,4.000000
168,130,Vikram,Mumbai,-5.000000,-500,Card,NaT,1.000000
169,130,Rahul,Kolkata,53.000000,-500,Card,NaT,3.000000

In [42]:
from scipy import stats
num_col=df1.select_dtypes(include=["int64","float64"]).columns
z_score=df1[num_col].apply(stats.zscore)
df_cleaned=df1[(z_score.abs()<=3).all(axis=1)]
df_cleaned

,Customer_ID,Customer_Name,City,Age,Order_Amount,Payment_Method,Order_Date,Rating
0,124,Rahul,Delhi,120.000000,-500,Wallet,2025-01-23,2.000000
1,132,Ravi,Bangalore,26.000000,-500,Card,NaT,2.985915
2,104,Priya,delhi,53.000000,-500,COD,2025-02-09,2.000000
3,135,Sneha,delhi,-5.000000,99999,UPI,2025-01-06,4.000000
4,140,Amit,delhi,57.273438,99999,UPI,2025-01-13,2.000000
...,...,...,...,...,...,...,...,...
165,138,Anjali,delhi,-5.000000,99999,Card,NaT,2.000000
166,128,Kavya,Delhi,42.000000,99999,Wallet,NaT,5.000000
167,129,Amit,delhi,57.000000,99999,Wallet,2025-02-05,4.000000
168,130,Vikram,Mumbai,-5.000000,-500,Card,NaT,1.000000
169,130,Rahul,Kolkata,53.000000,-500,Card,NaT,3.000000

In [44]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df4["Delivery_Time_Normalized"] = scaler.fit_transform(df4[["Delivery_Time"]])

In [47]:
df4.groupby("City")["Delivery_Time"].mean()

City
Bangalore    66.428571
Chennai      64.526316
Delhi        82.666667
Hyderabad    75.151515
Mumbai       86.114286
Name: Delivery_Time, dtype: float64

In [50]:
df1.groupby("City")["Order_Amount"].sum().idxmax()

'delhi'